<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <RootNamespace>SahelBundleKeyboard.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SahelBundleKeyboard.Core\SahelBundleKeyboard.Core.csproj" />
  </ItemGroup>

</Project>
